from Foo1 import*

path1 = input("Name of the first file: ")
print("Enter your text. To finish entering ***.\n")
inFile(path1)
path2 = input("Name of the second file: ")
print("Enter your text. To finish entering ***.\n")
inFile(path2)
path3 = input("Name of the third file: ")
rows = compare(path1, path2, path3)
print("The first text:")
outFile(path1)
print("The second text:")
outFile(path2)
print("The third text:")
outFile(path3)
print(f"The number of lines: {rows}")